app/models.py
from server import db
from sqlalchemy.sql import func

class UploadedData(db.Model):
    __tablename__ = 'uploaded_data'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    filename = db.Column(db.String(255), nullable=False)
    description = db.Column(db.String(255), nullable=False)
    uploaded_date = db.Column(db.DateTime(timezone=True), server_default=func.now())
    uploaded_by = db.Column(db.String(255))

app/analytics/__init__.py
from flask import Blueprint

analytics = Blueprint('analytics', __name__, url_prefix='/analytics')

from . import views

app/analytics/views.py
import urllib
import os
import pandas as pd
from flask import render_template, jsonify, request, redirect, url_for

from . import analytics
from server import datafiles, app, db
import models

ALLOWED_EXTENSIONS = set(['txt', 'csv', 'xls', 'xlsx'])

@analytics.route('/', methods=['POST', 'GET'])
def upload():
    if 'POST' == request.method and 'datafile' in request.files:
        filename = datafiles.save(request.files['datafile'])
        description = request.form['description']
        # need to handle failed upload
        upload = models.UploadedData(filename=filename, description=description)
        db.session.add(upload)
        db.session.commit()
        print('finished uploading..')
        return redirect(url_for('analytics.inspect_data', filename=filename))
    else:
        all_uploads = models.UploadedData.query.all()
    return render_template('analytics/upload.html', all_uploads=all_uploads)


@analytics.route('/data/inspect/')
def inspect_data():
    filename = request.args.get('filename', None)
    if filename:
        datafile = os.path.join(app.config['UPLOADED_DATAFILES_DEST'], filename)
        return render_template('analytics/inspect.html', datafile=datafile, filename=filename)
    return '<h1>No file was specified.</h1>'


@analytics.route('/api/inspect')
def api_inspect_data():
    datafile = request.args.get('datafile', None)
    print('inspecting file', datafile)
    if datafile:
        df = pd.read_excel(datafile)
        data = []
        for col in df.columns:
            # colname, dtype, count, included
            data.append([col, str(df[col].dtypes), int(df[col].count()), True])
        return jsonify(data)

app/antibiogram/__init__.py
from flask import Blueprint

antibiogram = Blueprint('antibiogram', __name__, url_prefix='/antibiogram')

from . import views

app/antibiogram/views.py
from flask import render_template
from . import antibiogram as abg

@abg.route('/')
def index():
    return render_template('antibiogram/index.html')

app/main.py
activate_this = '/Users/likit/.virtualenvs/biolytics/bin/activate_this.py'
exec(open(activate_this).read(), dict(__file__=activate_this))

from time import sleep
from threading import Thread

import webview
from server import run_server

def url_ok(url, port):
    try:
        from http.client import HTTPConnection
    except ImportError:
        from httplib import HTTPConnection

    try:
        conn = HTTPConnection(url, port)
        conn.request("GET", "/")
        r = conn.getresponse()
        return r.status == 200
    except:
        return False


if __name__ == '__main__':
    t = Thread(target=run_server)
    t.daemon = True
    t.start()

    while not url_ok("127.0.0.1", 5000):
        sleep(0.1)


    webview.create_window("Biolytics", "http://127.0.0.1:5000",
        resizable=True, width=1024, height=800, confirm_quit=True)

app/templates/analytics/inspect.html
{% extends "base.html" %}
{% block page_content %}
<section class="section">
    <div class="container">
        <div class="box">
            <h3 data-bind="visible: notDoneLoading()">Please wait while the data is being inspected...</h3>
            <table id="myTable" class="display" width="100%">
              <thead>
                <tr>
                  <th>Column Name</th>
                  <th>Data Type</th>
                  <th>Number of Values</th>
                  <th>
                    <span class="icon">
                      <i class="fas fa-check"></i>
                    </span>Keep
                  </th>
                </tr>
              </thead>
              <tbody data-bind="foreach: headers">
                <tr data-bind='css: {"has-text-grey-lighter": !$data[3]()}'>
                  <td data-bind="text: $data[0]()"></td>
                  <td data-bind="text: $data[1]()"></td>
                  <td data-bind="text: $data[2]()"></td>
                  <td><input type="checkbox" data-bind="checked: $data[3]"></td>
                </tr>
              </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="text/javascript">
    $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    var ViewModel = function() {
        var self = this;
        self.notDoneLoading = ko.observable(true);
        self.headers = ko.observableArray([]);
    }
    var vm = new ViewModel();
    ko.applyBindings(vm);
    $.get($SCRIPT_ROOT+'/analytics/api/inspect', {'datafile': {{datafile|tojson|safe}} }).done(function(data) {
      vm.notDoneLoading(false);
      $.each(data, function(idx, d) {
        var items = [];
        $.each(d, function(i, item) {
          items.push(ko.observable(item));
        });
        vm.headers.push(items);
      });
      var table = $('#myTable').DataTable();
    });
  </script>
{% endblock %}

app/templates/analytics/upload.html
{% extends "base.html" %}
{% block page_content %}
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <div class="box">
          <p>Supported formats: .txt, .csv, .tsv, .xls, .xlsx</p>
          <form enctype="multipart/form-data" method="post">
            <div class="field">
              <label class="label">Description</label>
              <div class="control">
                <textarea name="description" required></textarea>
              </div>
            </div>
            <div class="field">
              <label class="label">Upload</label>
              <div class="control">
                <input type="file" name="datafile" required>
              </div>
            </div>
            <div class="field">
              <button type="submit" value="submit">Upload</button>
            </div>
          </form>
        </div>
      </div>
      <div class="column">
        <div class="box">
          <p><strong>Uploaded Files</strong> <small>Click to inspect.</small></p>
          <table class="table is-striped">
            <tbody>
            {% for file in all_uploads %}
                <tr>
                  <td>
                    <span class="icon">
                      <i class="fas fa-file-excel"></i>
                    </span>
                  </td>
                  <td><a href="{{ url_for('analytics.inspect_data', filename=file.filename) }}">
                    {{ file.filename }}</a></td>
                    <td>{{ file.uploaded_date }}</td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}
{% block scripts %}
{% endblock %}

app/templates/antibiogram.html
{% extends "base.html" %}
{% block page_content %}
  <section class="section">
    <div class="container">
          <div class="box">
            <h1 class="title">Welcome to Biolytics</h1>
            <a href="https://www.google.com">Google.com</a>
          </div>
    </div>
  </section>
{% endblock %}

app/templates/antibiogram/index.html
{% extends "base.html" %}
{% block page_content %}
<section class="section">
    <div class="container">
        <h1 class="title">Antibiogram Page</h1>
    </div>
</section>
<section class="section">
    <div class="container">
      <div class="notification">
        <canvas id="myChart" class="has-shadow"></canvas>
      </div>
    </div>
</section>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="text/javascript">
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ["January", "February", "March", "April", "May", "June", "July"],
            datasets: [{
                label: "My first dataset",
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: [0, 10, 5, 2, 20, 30, 45],
            }]
        },
        options: {}
      });
</script>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.css') }}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
    <script src="{{ url_for('static', filename='js/fontawesome-all.min.js') }}" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <title>Antibiogram</title>
</head>
<body>
{% block navbar %}
    <nav class="navbar has-shadow is-light">
        <div class="navbar-brand">
            <a class="navbar-item" href="https://bulma.io">
                <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
            </a>
            <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>

        <div id="navbarExampleTransparentExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="/">
                    Home
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link" href="#">
                        Antibiogram
                    </a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{{ url_for('antibiogram.index') }}">
                            Overview
                        </a>
                        <a class="navbar-item" href="https://bulma.io/documentation/modifiers/syntax/">
                            Modifiers
                        </a>
                        <a class="navbar-item" href="https://bulma.io/documentation/columns/basics/">
                            Columns
                        </a>
                        <a class="navbar-item" href="https://bulma.io/documentation/layout/container/">
                            Layout
                        </a>
                        <a class="navbar-item" href="https://bulma.io/documentation/form/general/">
                            Form
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="https://bulma.io/documentation/elements/box/">
                            Elements
                        </a>
                        <a class="navbar-item is-active" href="https://bulma.io/documentation/components/breadcrumb/">
                            Components
                        </a>
                    </div>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link" href="#">
                      Analytics
                    </a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{{ url_for('analytics.upload') }}">
                          Upload data
                        </a>
                    </div>
                </div>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a class="bd-tw-button button" data-social-network="Twitter" data-social-action="tweet" data-social-target="http://localhost:4000" target="_blank" href="https://twitter.com/intent/tweet?text=Bulma: a modern CSS framework based on Flexbox&amp;hashtags=bulmaio&amp;url=http://localhost:4000&amp;via=jgthms">
                    <span class="icon">
                      <i class="fab fa-twitter"></i>
                    </span>
                                <span>
                      Tweet
                    </span>
                            </a>
                        </p>
                        <p class="control">
                            <a class="button is-primary" href="https://github.com/jgthms/bulma/archive/0.5.1.zip">
                    <span class="icon">
                      <i class="fas fa-download"></i>
                    </span>
                                <span>Download</span>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </nav>
{% endblock %}
{% block page_content %}
{% endblock %}
{% block scripts %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout/3.2.0/knockout-min.js"></script>
  <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/knockout.mapping/2.4.1/knockout.mapping.min.js"></script>
{% endblock %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block page_content %}
  <section class="hero is-large is-dark is-bold">
    <div class="hero-body">
      <div class="container">
        <h1 class="title">Biolytics Black Panther 0.1</h1>
        <h2 class="subtitle">
          Microbiological data management and analytics system
        </h2>
        <p>
          <button class="button is-dark is-rounded">Register</button>
          <button class="button is-dark is-rounded">Learn More</button>
        </p>
      </div>
    </div>
  </section>
  <footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <p>
          <strong>Biolytics Black Panther v.0.1</strong>
          <br>
          Faculty of Medical Technology, Mahidol University
          <br>
          Copyright 2018
        </p>
      </div>
    </div>
  </footer>
{% endblock %}

app/templates/uploads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload Data File</title>
</head>
<body>
    <section class="section">
        <form method="post" enctype="multipart/form-data" action="{{ url_for('upload') }}">
            <input type="file" name="datafile">
            <button type="submit" value="submit">Upload</button>
        </form>
    </section>
</body>
</html>